IF
  Heard([ANYONE],500)
THEN
  RESPONSE #100
    Enemy()
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(LastHeardBy(Myself)),20)
END

IF
  See(NearestEnemyOf(Myself))
THEN
  RESPONSE #100
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),20)
END

IF
  AttackedBy([PC],DEFAULT)
THEN
  RESPONSE #100
    Enemy()
    Shout(500)
    EquipMostDamagingMelee()
    AttackReevaluate(NearestEnemyOf(Myself),20)
END

